version: 1
threads: 4
pid_file: /tmp/carrier2.pid
error_log: /tmp/carrier.log
upgrade_sock: /tmp/carrier2.sock
upstream_keepalive_pool_size: 100
# probes: 
#   httpGet:
#       - 8001
#       - 8002
# proxy:
#   - port: 5002
#     tls:
#       certificate: "/path/to/ca.crt"
#       key: "/path/to/key.pem"
#       sni: "host.blueshoe.io"
#     clusterUpstream: 
#       - "10.42.0.17:5002"
#     bridges:
#         user-1:
#             endpoint: "www.blueshoe.io:443"
#             tls: true
#             sni: "www.blueshoe.io"
#             rules:
#                 - match:
#                     - matchHeader:
#                         name: "x-gefyra"
#                         value: "user-1"
#                     and
#                     - matchPath: 
#                         path: "/my-svc"
#                         type: "prefix"
#                 or
#                 - match:
#                     - matchPath:
#                         path: "/always"
#                         type: "prefix"
