# This workflow creates a PR for the formula update

name: Update Homebrew formula

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Build OSX binary"]
    types: [completed]

jobs:
  update_homebrew:
    runs-on: macos-11
    if: ${{ github.event.workflow_run.event == 'release' }}
    steps:
    - uses: actions/checkout@v3
    - name: Update Homebrew formula
      working-directory: client/
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_TOKEN }}
      run: |
        export APP_VERSION=`cat pyproject.toml | grep version -m 1 | awk '{ print substr($3, 2, length($3) -2)}'`
        brew tap gefyrahq/gefyra
        echo $APP_VERSION
        brew bump-formula-pr --version=$APP_VERSION gefyra
